### ISSUE TITLE
6.2.4 install failed

### ISSUE THREAD

**Issue by like-inspur** [pjhampton/kibana-prometheus-exporter#10]
I start kibana by docker with image sebp/elk-plugin:6.2.4, then I execute kibana-plugin install command:
root@5dd3dbe4a8fa:/# /opt/kibana/bin/kibana-plugin install http://10.110.17.48/monitor/kibana-prometheus-exporter-6.2.4.zip
Attempting to transfer from http://10.110.17.48/monitor/kibana-prometheus-exporter-6.2.4.zip
Transferring 41471 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.
   4286 modules
    
    ERROR in /opt/kibana/optimize/bundles/prometheus-exporter.entry.js
    Module not found: Error: Can't resolve 'plugins/kibana-prometheus-exporter/app' in '/opt/kibana/optimize/bundles'

root@5dd3dbe4a8fa:/# /opt/kibana/bin/kibana-plugin list
prometheus-exporter@1.0.0

But when I restart container, I found that kibana can't start, the log is like this:
{"type":"log","@timestamp":"2018-06-29T08:25:15Z","tags":["info","optimize"],"pid":312,"message":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timelion, prometheus-exporter and kibana. This may take a few minutes"}

**Comment by pjhampton** [comment]
Hi @like-inspur 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.2.4

I have removed the bug and updated the package. Thanks
