### ISSUE TITLE
Remove UI

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/kibana-prometheus-exporter#108]
Remove UI from the app. Users don't see the point in the UI anymore as the point of this app is to export machine-readable metrics.

**Comment by zcharleshebert** [comment]
Hello there, I would like to help you with that.

**Comment by pjhampton** [comment]
Ok, @zcharleshebert. It's all yours.

**Comment by zcharleshebert** [comment]
@pjhampton thought that would be a pretty easy one but I actually failed to setup a Kibana dev env for your plugin. That said, I'm sorry for not trying that in the first place. 
I'll pass to someone used to it.

**Comment by pjhampton** [comment]
That's no problem @zcharleshebert

**Comment by pjhampton** [comment]
Doesn't seem like anyone wants to take this up. I will get rid of it in the 7.4.0 release trunk.
