### ISSUE TITLE
Missing release artefact for tag 7.3.2

### ISSUE THREAD

**Issue by lazyusername** [pjhampton/kibana-prometheus-exporter#119]
You are [referencing release artefact for tag 7.3.2](https://github.com/pjhampton/kibana-prometheus-exporter/commit/94ebd0182dfb7b846e9183907eb4dd4d06c8b2a6#diff-04c6e90faac2675aa89e2176d2eec7d8R48)  but it's actually completely missing. Just check out the url in the commit to release => 404.

/cc @dibyadas

**Comment by pjhampton** [comment]
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.3.2

Thanks for letting me know @lazyusername! ❤️ this has been resolved.
