### ISSUE TITLE
6.2.4 Error 404

### ISSUE THREAD

**Issue by yehaolan** [pjhampton/kibana-prometheus-exporter#12]
After I installed the kibana-prometheus-exporter plugin, I got Error 404 when I tried to access `http://localhost:5601/_prometheus/metrics`

```
bash-4.2$bin/kibana-plugin list
kibana-prometheus-exporter@1.0.0

bash-4.2$ curl http://localhost:5601/_prometheus/metrics
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

I wonder what else I need to do in order to get it viewed on the kibana dashboard.

**Comment by pjhampton** [comment]
Hey @yehaolan 

I just ran `bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.2.4/kibana-prometheus-exporter-6.2.4.zip` and checked it out. Seems fine. 

Are you running in a container or behind a proxy by any chance?

**Comment by yehaolan** [comment]
Yes. My Kibana is deployed via this [yaml file](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/kibana-deployment.yaml), and there is a Nginx deployed in front of the Kibana container. 

How should I solve that problem?

**Comment by pjhampton** [comment]
Thanks @yehaolan - How exactly are you installing this plugin?

**Comment by yehaolan** [comment]
Right now, I installed it with `bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.2.4/kibana-prometheus-exporter-6.2.4.zip` after I get the shell with `kubectl exec -it <kibana container> bash`.

**Comment by yehaolan** [comment]
@pjhampton Any updates on the problems that getting 404?

**Comment by pjhampton** [comment]
Hey @yehaolan 

I have just downloaded *6.2.4* ES and Kibana. I then installed the plugin in the same way and it was fine.

1) Did you install the plugin while kibana was running? If so, can you restart?
2) Could the install have been interupted?

<img width="1280" alt="screen shot 2018-07-16 at 22 03 32" src="https://user-images.githubusercontent.com/8960296/42783495-29998dde-8944-11e8-91a0-11db5d64d665.png">

**Comment by yehaolan** [comment]
Solved. I am sure running 6.2.4. I added one more layer to the kibana image which installs the plugin, and then I used that image for deployment. Thanks for your help!
