### ISSUE TITLE
v 7.3.1 - Prometheus button bugged out on the sidebar

### ISSUE THREAD

**Issue by matagyula** [pjhampton/kibana-prometheus-exporter#121]
I'm using version 7.3.1 (downloaded as kibana-prometheus-exporter-7.3.1.zip) of the exporter, with Elasticsearch and Kibana versions 7.3. Is there a way to hide the faded Prometheus button from the sidebar? While it is clickable, in my case no actual content loads, just an empty page. With that said, the exporter itself works (as discussed in another issue thread).
![image](https://user-images.githubusercontent.com/38976086/69148964-c523f000-0ad5-11ea-9b88-4bac4b06101a.png)
Thank you!
PS: The feature can't be disabled in the Space settings (Customize feature display), as it's not listed there.

_Originally posted by @matagyula in https://github.com/pjhampton/kibana-prometheus-exporter/issues/77#issuecomment-555499387_

**Comment by pjhampton** [comment]
Acknowledged :) will work on tonight

**Comment by pjhampton** [comment]
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.3.1-v2

**Comment by matagyula** [comment]
Thank you, @pjhampton! I've deployed the update today, everything works great so far. Cheers!

**Comment by pjhampton** [comment]
No problemo @matagyula 👍 let me know if anything comes up or have any questions. If you have feedback for extra features etc, let me know too.
