### ISSUE TITLE
Can't install 6.5.2

### ISSUE THREAD

**Issue by luxie11** [pjhampton/kibana-prometheus-exporter#139]
Hey, 
Thank you for creating a Prometheus Metrics exporter for Kibana, but when I'm trying to install on same VM, where kibana is installed, i get EACCES: permission denied, open '/usr/share/kibana/optimize/.babel_register_cache.json'.
![image](https://user-images.githubusercontent.com/29857050/74946866-9da93000-5402-11ea-841c-1124fd5693dd.png)

Thank you for the answer.

Kind regards.

**Comment by pjhampton** [comment]
Hey @luxie11. Checking...

**Comment by pjhampton** [comment]
I downloaded 6.5.2 and had no problems installing or running it. See my tmux session screenshots below. I suspect there was an issue with the installation.

Can you please try again and let me know if this reoccurring? Have you see this? https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

<img width="1280" alt="Screenshot 2020-02-20 at 19 22 20" src="https://user-images.githubusercontent.com/8960296/74971101-714bde80-5417-11ea-99ab-398a7427a519.png">


<img width="1280" alt="Screenshot 2020-02-20 at 19 26 46" src="https://user-images.githubusercontent.com/8960296/74971123-7872ec80-5417-11ea-9a00-dfd3fcd12a63.png">

**Comment by luxie11** [comment]
Actually after some time I found a bug. It's a mistake, I tried to install this service with other user, who can't doesn't have permissions for kibana files. Thats why I got a bug. 
After I installed it on Linux i tried curl the localhost, but I got redirect to login. It is supose to happen or not?

**Comment by pjhampton** [comment]
Hey @luxie11 

Ok. That makes sense :-) easy mistake
Have you seen this? https://github.com/pjhampton/kibana-prometheus-exporter#x-pack--ssl--basic-auth

**Comment by luxie11** [comment]
Hey again, 
Yes I checked it, so change logins in this file and everything will be fine?

**Comment by pjhampton** [comment]
Try it and let me know :-)

**Comment by pjhampton** [comment]
Hey @luxie11. How did it work out?

**Comment by luxie11** [comment]
Hey @pjhampton I will try it on Monday

**Comment by luxie11** [comment]
Hey again, i changed the kibana.yml config file with new username and pass, but still getting response like this using curl -v command. 

![image](https://user-images.githubusercontent.com/29857050/75134658-9d9d7e80-56e7-11ea-80f1-b06e39789372.png)

**Comment by luxie11** [comment]
Hey @pjhampton,  so I add params to config file and tried to curl the url, but i get redirection error. 
![image](https://user-images.githubusercontent.com/29857050/75135572-9d52b280-56ea-11ea-949c-afe16a1f6a1e.png)

**Comment by luxie11** [comment]
However, using wget I get files from URL with _prometheus/metrics file, but how to check if it's really working?

**Comment by pjhampton** [comment]
Hiya @luxie11 

I think I understand. You can get that with`curl -XGET http://<username>:<password>@localhost:5601/_prometheus/metrics` where `<username>` and `<password>` are those things :-) 

Regarding how to check if it is really working I suppose you could connect it to prometheus. Let me know how you get on!

**Comment by luxie11** [comment]
Hey @pjhampton 
I managed to test it with curl command using curl -u user:pass http://localhost:5601/_prometheus/metrics ant it's working. Thanks for help :)

**Comment by pjhampton** [comment]
No problemo, @luxie11. Glad I could help!
