### ISSUE TITLE
Support Kibana v7.6.1

### ISSUE THREAD

**Issue by olgakorichkovskaya** [pjhampton/kibana-prometheus-exporter#141]
Please add support Kibana v7.6.1

**Comment by pjhampton** [comment]
Hey @olgakorichkovskaya 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.6.1

Thanks 🙏

**Comment by olgakorichkovskaya** [comment]
@pjhampton  Thanks a lot for a really quick update.
