### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by dietrich-h** [pjhampton/kibana-prometheus-exporter#147]
thanks Pete, my colleague Walter and myself are hoping to get the plugin working to instrument our kibana stack.

It looks as though the installation was successful but when we try to curl the plugin endpoint  nothing is returned.

Are the authentication credentials in the kibana.yml necessary for the plugin to start working?  

Should we be able to retrieve the exporter endpoint like so:
curl http://localhost:5601/_prometheus/metrics

We're getting an EOF error on the prometheus side will trying to pull data from the pluging, most likely because nothing is listening?

Thanks for your help!

-Dietrich

**Comment by dietrich-h** [comment]
we managed to get this working, thanks for your help!

**Comment by pjhampton** [comment]
Hey @dietrich-h. Glad you and walter got this working 👍
take it easy

**Comment by LH8PPL** [comment]
Hey, i got the same problem, how did you solve it?

**Comment by pjhampton** [comment]
@LH8PPL Hey! 

Can you please open another issue with your:

  - Stack version
  - Installation details including the plugin version
  - What you believe the problem to be

.. and we will debug together from there!
