### ISSUE TITLE
Can access the /_prometheus/metrics without authentication when enable basic xpack?

### ISSUE THREAD

**Issue by royoan** [pjhampton/kibana-prometheus-exporter#152]
We have install kibana with basic xpack, can we access the metric without authentication?

**Comment by pjhampton** [comment]
Hey @royoan 👋 

Yep! If no auth is enabled then you can install and it should _just work_.
If auth is enabled you can follow the instructions here: https://github.com/pjhampton/kibana-prometheus-exporter#ssl--basic-auth
