### ISSUE TITLE
Kibana 7.3.3

### ISSUE THREAD

**Issue by tarekesmail** [pjhampton/kibana-prometheus-exporter#157]
Hi, 
I can't find my kibana version 7.3.3 in plugins, can you help please

**Comment by pjhampton** [comment]
Hey @tarekesmail 

Sure thing. I will drop an artifact and get back to you later on.

**Comment by pjhampton** [comment]
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.3.3
