### ISSUE TITLE
Support Kibana 5 series

### ISSUE THREAD

**Issue by zqc0512** [pjhampton/kibana-prometheus-exporter#16]
not support es 5.x ?
in releaes i don't find with es 5.x zip file?
is not support?

**Comment by pjhampton** [comment]
I didn't plan to @zqc0512 but I can do if there is demand for it. What version are you using and I can create something... :smile:

**Comment by zqc0512** [comment]
thanks, so.
as es 5.6.8 or the new es 5.6.11
@pjhampton

**Comment by pjhampton** [comment]
Ok, no problem. I will sort this out tonight (my time - GMT)

**Comment by zqc0512** [comment]
thanks.  with update @ me

**Comment by pjhampton** [comment]
Hey @zqc0512 

I'm afraid Kibana 5 doesn't support a public stats API. So it's quite a substantial piece of work as I / we would need to traverse the DOM and pull all the values out of http://localhost:5601/status#?_g=()

I am interested in supporting the 5 series but it won't be likely until the weekend

**Comment by iankittomar** [comment]
I am also using 5.6.6, I need a support too :)

**Comment by pjhampton** [comment]
No problem @iankittomar :smile: I'm going to support the entire series so I will ping you both when I'm ready to ship.

**Comment by pjhampton** [comment]
@zqc0512 Goog news - https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/5.6.8
