### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by davejhahn** [pjhampton/kibana-prometheus-exporter#169]
I have Kibana installed (using BItnami's Helm Chart, latest version which installs 7.8.0 of Kibana) and used the plugins value passed in to install kibana-prometheus-exporter, and I'm getting a 404 error on the endpoint both in Prometheus and on the pod directly using curl.

e.g.
``````
--set plugins[0]=https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.8.0/kibana-prometheus-exporter-7.8.0.zip
``````

It installed the plugin (visible in /opt/bitnami/kibana/plugins/kibana-prometheus-exporter) but my Prometheus Target Endpoint for it shows 404.

Also, on the pod, I tried:  
``````
curl http://10.244.2.170:5601/_prometheus/metrics  (pod IP) and http://127.0.0.1:5601/_prometheus/metrics 
``````
and both return: 
``````
 bash http://127.0.0.1:5601/_prometheus/metrics: No such file or directory
``````

I tried installing it on the pod just in case it wasn't really installed:
``````
./kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.8.0/kibana-prometheus-exporter-7.8.0.zip
``````
And it says:
``````
Plugin kibana-prometheus-exporter already exists, please remove before installing a new version.  
``````
package.json in /opt/bitnami/kibana/plugins/kibana-prometheus-exporter says it is the version I expected it to be, 7.8.0

Kibana itself is working fine, can access it without any problems and curl call on the pod returns the content, just not the plugin.

Any idea what my problem might be?

Thanks.

**Comment by pjhampton** [comment]
Hey. 

I'm sorry, I have no idea - this is the first I have heard of Helm Charts. It seems that the downloads for 7.8.0 are quite a lot and frequent so I can only assume it is working. The helm charts people will probably be able to advise. 
If you do get it figured out I would appreciate if you could drop the details in this issue so other people can benefit :-)
