### ISSUE TITLE
Installing Plugin in v5.6.6

### ISSUE THREAD

**Issue by iankittomar** [pjhampton/kibana-prometheus-exporter#18]
I'm Installing plugins and at 'optimizing and caching browser bundles', its stuck more than a couple of hours.
A screenshot is attached.
![kibanaerror](https://user-images.githubusercontent.com/34299541/45475831-c0c7ae80-b73d-11e8-939c-183f4a5f7d36.png)

**Comment by iankittomar** [comment]
and how do I change the path from 'http://localhost:5601/_prometheus/metrics' to 'http://localhost:5601/metrics' ? in

**Comment by pjhampton** [comment]
Hey @iankittomar 

Can you please tell me more about your environment. It does indeed take a little while to optimize - but a couple of hours is crazy time. 

> and how do I change the path from 'http://localhost:5601/_prometheus/metrics' to 'http://localhost:5601/metrics' ? in

You can't. You can fork the code and expose the uri else where

**Comment by iankittomar** [comment]
I am using HashiCorp 'Consul' as I have used /metrics as default for my all services. So, in this case, ist /_prometheus/metrics so Prometheus is not able to fetch the metrics and with default /metrics, path and service remains down, 

So, the question is can you change /_prometheus/metrics to /metrics which helps me to use metrics and create a Dashboard in Grafana.

Thanks

**Comment by amithrh** [comment]
@iankittomar you can clone the zip , chnage the all the _prometheus/metrics to /metrics and then install the new zip

**Comment by pjhampton** [comment]
That's correct. Thanks @amithrh 

@iankittomar as for why it's taking hours - I'm perplexed to be honest. Should take no more than a couple of minutes.

**Comment by pjhampton** [comment]
Reopening for investigation

**Comment by pjhampton** [comment]
@iankittomar what is the deal with

```
bin/kibana-plugin install kibana.zip
```

can you please try:

```
bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/5.6.6/kibana-prometheus-exporter-5.6.6.zip
```

**Comment by iankittomar** [comment]
@pjhampton  I need default metrics path i.e /metrics, so I have changed a file server/routes and then again created .zip file after that I am using `bin/kibana-plugin install kibana.zip` to use my change configuration.

if I will use `bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/5.6.6/kibana-prometheus-exporter-5.6.6.zip` which means my problem won't get solved I will get/_prometheus/metrics as a path

**Comment by pjhampton** [comment]
Just to let you know, this feature has been added, it just needs to be merged back in time and rereleased.

**Comment by pjhampton** [comment]
I'm going to close this for now and backport soon.
