### ISSUE TITLE
The credentials are encoded in a Base64 header when sent over the wire

### ISSUE THREAD

**Issue by lianfulei** [pjhampton/kibana-prometheus-exporter#182]
How to use HTTP access？

http://172.16.3.1:5601/_prometheus/metrics

**Comment by pjhampton** [comment]
I don't understand you question, @lianfulei 
Please rephrase.

> The credentials are encoded in a Base64 header when sent over the wire

Yes, it's a request to the same host. If you are worried about packet sniffing you should enable TLS too.

**Comment by lianfulei** [comment]
Kibana has enabled x-pack. If you visit this link, you will be prompted to log in your account and password. Can you not enter your account password?

http://172.16.3.1:5601/_prometheus/metrics

**Comment by lianfulei** [comment]
@pjhampton

**Comment by pjhampton** [comment]
Yeah, see https://github.com/pjhampton/kibana-prometheus-exporter#ssl--basic-auth

Just put a user/pass in the Kibana config like so:

```
kibana-prometheus-exporter.user: <user>
kibana-prometheus-exporter.pass: <password>
```

**Comment by lianfulei** [comment]
kibana-prometheus-exporter.user: kibanaUser
kibana-prometheus-exporter.pass: ohSoSecret!

**Comment by lianfulei** [comment]
@pjhampton

**Comment by lianfulei** [comment]
My version is 7.6.2

**Comment by pjhampton** [comment]
No, you need to create a new user. Those are only example values. See https://www.elastic.co/guide/en/elasticsearch/reference/current/get-started-users.html

The version doesn't matter - the process is the same.

**Comment by lianfulei** [comment]
i know。The account and password are correct，but  visit http://172.16.3.1:5601/_prometheus/metrics，302 jump to http://172.16.3.1:5601/login?next=%2F_prometheus%2Fmetrics

how to solve？

**Comment by lianfulei** [comment]
@pjhampton

**Comment by pjhampton** [comment]
Is it behind an nginx, haproxy or other reverse proxy?

**Comment by lianfulei** [comment]
xpack It's on

**Comment by lianfulei** [comment]
@pjhampton

**Comment by lianfulei** [comment]
Is there a way not to log in？

**Comment by pjhampton** [comment]
```
curl -XGET -u username:password  http://172.16.3.1:5601/_prometheus/metrics
```
Should work. And then in your scrape configs on your prometheus server you would set the auth there:

```
# Sets the `Authorization` header on every scrape request with the
# configured username and password.
# password and password_file are mutually exclusive.
basic_auth:
  [ username: <string> ]
  [ password: <secret> ]
  [ password_file: <string> ]
```

See: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Comment by lianfulei** [comment]
it works

I feel dizzy. This is actually the same as the elasticsearch API.

**Comment by lianfulei** [comment]
thanks

**Comment by lianfulei** [comment]
I asked a few questions, which had nothing to do with the subject

How do I add this to prometheus.yml
http://192.168.1.2/-/metrics?token=NsdfwerSDDD53MC
@pjhampton

**Comment by lianfulei** [comment]
i know.This should be used

# Optional bearer token authentication information.
[ bearer_token: <secret> ]
