### ISSUE TITLE
kibana-prometheus-exporter-Version-7.3.2 -Showing npm update log

### ISSUE THREAD

**Issue by kovurusaisachin** [pjhampton/kibana-prometheus-exporter#202]
Hi,
      I'm using the kibana-7.3.2 version and I tried using the Kibana-Prometheus exporter of the same version(7.3.2). After installing Kibana I have checked whether the kibana-plugin got successfully deployed or not using the kibana-plugin list (by using exec command) inside the container. I'm able to see the kibana-prometheus_exporter.But the issue is I'm getting the logs like below where after a certain time it's restarting the POD.Is there anything that I have missed?

{"type":"log","@timestamp":"2021-01-06T04:12:26Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

Logs:
  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately

Thanks in Advance.

**Comment by pjhampton** [comment]
Hey @kovurusaisachin 

Sorry for the tardy reply. I have been very busy recently.
7.3.2 [was released Sept 12 2019](https://github.com/elastic/elasticsearch/releases/tag/v7.3.2). Do you not have plans to upgrade? I suggest you do for modern features and security fixes.

After a little googling - It seems that the only way around this is to cut another release for this version. Is that what you would prefer instead of upgrading your stack?

**Comment by kovurusaisachin** [comment]
Hey @pjhampton, down the road we have plans of upgrading the stack to the newer version. But till then, it would be helpful If I could get any workaround for the existing(7.3.2) version.

**Comment by pjhampton** [comment]
Ok, no problemo. I will cut you a new release over the next couple of days when I get a moment @kovurusaisachin 👍

**Comment by kovurusaisachin** [comment]
@pjhampton Thanks

**Comment by pjhampton** [comment]
Hey @kovurusaisachin, so I had a look into this. I think the devil is in the detail:

You say this is your output:

```
{"type":"log","@timestamp":"2021-01-06T04:12:26Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
```

^ This plugin (kibana-prometheus-exporter) isn't there. When I install my log looks like so:

```
log   [10:46:04.767] [info][optimize] Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, **kibana-prometheus-exporter**, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes
```

I also ran without installing the plugin and got the same output as you:

```
Desktop/elastix/kibana-7.3.2-darwin-x86_64 is 📦 v7.3.2 via ⬢ v15.4.0 
➜ bin/kibana
  log   [10:49:06.690] [info][plugins-system] Setting up [1] plugins: [translations]
  log   [10:49:06.696] [info][plugins][translations] Setting up plugin
  log   [10:49:06.697] [info][plugins-system] Starting [1] plugins: [translations]
  log   [10:49:10.751] [info][optimize] Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
```

And so on. So this is an issue with the dependencies in the Kibana codebase, not the plugin. 
I'm not a k8s expert (if that is the orchestrator you are using), but it sounds like your orchestrator is listening for command exit code that isn't graceful (non-0s). My recommended port of call is either - update your stack to a more recent version, or start killing your containers / draining pods on [specific exit codes such as 1](https://tldp.org/LDP/abs/html/exitcodes.html).  

https://github.com/elastic/sdh-kibana/issues/648#issuecomment-669548948

**Comment by pjhampton** [comment]
Hey @kovurusaisachin, so I had a look into this. I think the devil is in the detail:

You say this is your output:

```
{"type":"log","@timestamp":"2021-01-06T04:12:26Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
```

^ This plugin (kibana-prometheus-exporter) isn't there. When I install my log looks like so:

```
log   [10:46:04.767] [info][optimize] Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, **kibana-prometheus-exporter**, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes
```

I also ran without installing the plugin and got the same output as you:

```
Desktop/elastix/kibana-7.3.2-darwin-x86_64 is 📦 v7.3.2 via ⬢ v15.4.0 
➜ bin/kibana
  log   [10:49:06.690] [info][plugins-system] Setting up [1] plugins: [translations]
  log   [10:49:06.696] [info][plugins][translations] Setting up plugin
  log   [10:49:06.697] [info][plugins-system] Starting [1] plugins: [translations]
  log   [10:49:10.751] [info][optimize] Optimizing and caching bundles for graph, monitoring, space_selector, login, overwritten_session, logout, logged_out, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
```

And so on. So this is an issue with the dependencies in the Kibana codebase, not the plugin. 
I'm not a k8s expert (if that is the orchestrator you are using), but it sounds like your orchestrator is listening for command exit code that isn't graceful (non-0s). My recommended port of call is either - update your stack to a more recent version, or start killing your containers / draining pods on [specific exit codes such as 1](https://tldp.org/LDP/abs/html/exitcodes.html).
