### ISSUE TITLE
Release 7.10.1

### ISSUE THREAD

**Issue by jaronoff97** [pjhampton/kibana-prometheus-exporter#207]
Hello! Is there anything blocking the release for the exporter for 7.10.1? Thank you for writing this!

**Comment by pjhampton** [comment]
Hey @jaronoff97 

Thanks for reaching out! I'm just a little behind with life at the moment.
I will try to release this, this weekend

**Comment by pjhampton** [comment]
See https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.10.1

Tested. Please let me know if there are any issues! 
Take care
