### ISSUE TITLE
Kibana v6.4.1 got released

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#21]
@pjhampton Thanks in advance!

**Comment by pjhampton** [comment]
Thanks @nikolay 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.1

You may have to update your grafana dashboard (or whatever you are using to visualize) as there was a PR to make compatible with the new Prometheus minor release.

**Comment by nikolay** [comment]
Thank you very much, @pjhampton!
