### ISSUE TITLE
can not start kibana

### ISSUE THREAD

**Issue by hollden** [pjhampton/kibana-prometheus-exporter#211]
Hi! 
I am trying to install kibana exporter v. 7.10.0, but after successfull installation kibana does not start.
In journalctl I see this error: FATAL  Error: Cannot find module 'axios'
Can you help me?

**Comment by pjhampton** [comment]
Hey @hollden 

Can you tell me more about your setup?
Can you also paste me more logs if you have them?

**Comment by pjhampton** [comment]
I just updated the artifact: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.10.0
Can you please try that? I bundled axios with it

**Comment by hollden** [comment]
After your fix plugin has been installed properly, without any arrors, thank you!

**Comment by pjhampton** [comment]
Great. Thanks for reporting back.
