### ISSUE TITLE
Internal Server Error when Enables kibana SSL.

### ISSUE THREAD

**Issue by goldstrike77** [pjhampton/kibana-prometheus-exporter#215]
I have been using Kibana Prometheus exporter for several years, But find some changed from 7.10.

If I enable Kibana SSL, an internal server error occurs, it seems to use HTTP instead of HTTPS.

kibana: _currentUrl: 'http://127.0.0.1:5601/api/status' },
kibana: response: undefined,
kibana: isAxiosError: true,
kibana: toJSON: [Function: toJSON] }
kibana: error  [04:32:33.675]  Error: Internal Server Error

my config as following.

xpack.security.enabled: true
server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/ssl/server.crt
server.ssl.key: /etc/kibana/ssl/server.key
server.ssl.certificateAuthorities: /etc/kibana/ssl/ca-cert.pem
server.ssl.clientAuthentication: none
server.ssl.supportedProtocols: ["TLSv1.2"]
status.allowAnonymous: true

Thanks a lot.

**Comment by pjhampton** [comment]
That's correct - there was an entire rewrite of this plugin from 7.10.
Can you give me more information? Are you using the 7.10 package, or have you created your own from a fork?

**Comment by goldstrike77** [comment]
I've tried these versions, Judging by the syslog, Secured HTTP is not used when enable kibana ssl.

It can work normally after disable SSL.

kibanaPrometheusExporter-7.11.1.zip

**Comment by pjhampton** [comment]
Sorry to leave you hanging... I'm still looking into this

**Comment by pjhampton** [comment]
Thanks @goldstrike77. This should be fixed now! Sorry for the delay. 
Please try reinstalling that artifact
