### ISSUE TITLE
metric kibana_heap_max_in_bytes not the max heap from configuration

### ISSUE THREAD

**Issue by perkons** [pjhampton/kibana-prometheus-exporter#219]
CentOS Linux release 8.3.2011
opendistroforelasticsearch-kibana-1.13.1-1.x86_64

Heap configured:
```
# cat /etc/kibana/node.options 
## max size of old space in megabytes, default 1.4 GB
--max-old-space-size=1500
#
```

kibana_heap_max_in_bytes is changing frequently and is averaging 103MB over 1h, but the heap is set to 1500MB. Should this metric not show the max size in configuration?
I cannot write proper alerts in prometheues because of this.

In comparison this ES exporter https://github.com/vvanholl/elasticsearch-prometheus-exporter has the metric es_jvm_mem_heap_max_bytes and it is equal to heap size configured in ES.

**Comment by pjhampton** [comment]
Howdy @perkons 👋 

First up, what version of the plugin are you using? I'm really not that familiar with the open distro and haven't tested against this distribution. If others let me know I can start supporting it.

> kibana_heap_max_in_bytes is changing frequently and is averaging 103MB over 1h, but the heap is set to 1500MB. Should this metric not show the max size in configuration?

So the code doesn't do any processing of that number - we grab it out of the internal stats api and present it to the user. I wonder if the stats api is bust in that distro? You will be able to tell by hitting the URI `api/stats?extended`

**Comment by pjhampton** [comment]
> Should this metric not show the max size in configuration?

If I'm understanding you correctly you are expecting to see max heap in bytes be a constant line. 
So after a little research, I'm not sure it should. I believe the old space is managed by the v8 runtime and a process doesn't reserve heap ahead of time. I believe it to be a soft limit so other processes can use memory if that process is not using it. As it is a `--max` metric, I believe that is the upper bound that the process should die with an OOM exception.

**Comment by perkons** [comment]
Hi @pjhampton 

thank you for the fast answer! Sorry for the missing version, it is Opendistro 1.13.1 so it is ES 7.10.2 and the same version for the plugin.

And yes, I expect it to be a constant line until I reconfigure it similar as it is for ES (es_jvm_mem_heap_max_bytes). The difference is that for ES you can configure the min and max heap size. I will look at the API  `api/stats?extended`  tomorrow and report back.

**Comment by pjhampton** [comment]
Hey @perkons 

Just checking in on this, did you get to the bottom of this?

**Comment by perkons** [comment]
So I missed some other metrics because of wrong search:
```
{"process":{"memory":{"heap":{"total_bytes":124067840,"used_bytes":111204336,"size_limit":1526909922} ...
```
this is the first line from the result the api returns, but it matches exactly the metrics I posted above

**Comment by pjhampton** [comment]
🏅 <- this is for you @perkons. You were correct. So thank you 🙏

**Comment by perkons** [comment]
@pjhampton thank you very much! I will reinstall the plugin once it is released.

**Comment by pjhampton** [comment]
@perkons released 🚀

**Comment by perkons** [comment]
@pjhampton thank you very much!
