### ISSUE TITLE
Clarification on install

### ISSUE THREAD

**Issue by amithrh** [pjhampton/kibana-prometheus-exporter#24]
1. Does it require kibana rpm to be present for installation of this exporter ?
2. Will the metric be only seen in Kibana UI , an dnot in a seperate Promethues UI ( which is being run on different container )
3. Will there be any RPM release ?
4. Can i get instruction for offline installation ?

**Comment by pjhampton** [comment]
Hi @amithrh 

Thanks for writing in. Sorry for the delay! See below:

> 1. Does it require kibana rpm to be present for installation of this exporter ?

On CentOS / RHEL you can install kibana as [described here](https://www.elastic.co/guide/en/kibana/current/rpm.html).

> 2. Will the metric be only seen in Kibana UI , an dnot in a seperate Promethues UI ( which is being run on different container )

No, the UI promethues view is auxillary. You can see the prometheus metrics at http://localhost:5601/_prometheus/metrics

> 3. Will there be any RPM release ?

Not required :-)

> 4. Can i get instruction for offline installation ?

I assume you you are working in a box with no connection to the wider internet. You can just unzip the release package in `/usr/share/kibana/plugins`

**Comment by pjhampton** [comment]
Yeah, sorry that isn't support @amithrh

If you want you could always submit a PR if you think that would be a useful feature?

You could do it like so?
https://github.com/richardkippers/docker-elkx/blob/master/Dockerfile
