### ISSUE TITLE
KIbana ssl verification failed

### ISSUE THREAD

**Issue by andywow** [pjhampton/kibana-prometheus-exporter#25]
Hello, trying to open https://myhost:5061/_prometheus/metrics - got error 500.

In kibana logs i see:

`
Sep 25 14:06:43 sa5elk-kibana01 kibana[61671]: {"type":"error","@timestamp":"2018-09-25T11:06:43Z","tags":[],"pid":61671,"level":"error","error":{"message":"self signed certificate in certificate chain","name":"Error","stack":"Error: self signed certificate in certificate chain\n    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:639:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)","code":"SELF_SIGNED_CERT_IN_CHAIN"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"self signed certificate in certificate chain"}
`

I got CA certificated, from which i generated SSL certificate for kibana. CA certificate is installed on linux-server. In kibana settings i set `server.ssl.certificationAuthorities: [path_to_ca_cert]`. I got no errors about ssl in kibana, but got this exception in prometheus plugin.

**Comment by pjhampton** [comment]
Hey

Let me get back to you on this. There was a related issue which went stale: https://github.com/pjhampton/kibana-prometheus-exporter/issues/3

Do you have other plugins installed?

**Comment by andywow** [comment]
That issue #3 is about wrong-generated certificated - on my certificate i got correct hostname in it. I got latest elasticseach, kibana - `6.4.1`. And, yes, i got other plugins - `readonlyrest` on elasticsearch and `logtrail` on kibana.

**Comment by anandsinghkunwar** [comment]
Is there any update on this? @pjhampton

**Comment by pjhampton** [comment]
Hi @anandsinghkunwar - I'm afraid not. I haven't had the time as yet.

**Comment by pjhampton** [comment]
Hi @anandsinghkunwar / @andywow 

Is it the following the following that should be added to the request?

```
server.ssl.enabled: true
server.ssl.certificate: /path/to/your/server.crt
server.ssl.key: /path/to/your/server.key
```

I don't have a clear run to test.

**Comment by andywow** [comment]
Hi, @pjhampton,

i think, yes, i need this settings. But now i don't work with kibana, so i can't test

**Comment by pjhampton** [comment]
Closing this as there is now:

* https://github.com/pjhampton/kibana-prometheus-exporter/issues/3
* https://github.com/pjhampton/kibana-prometheus-exporter/issues/67
