### ISSUE TITLE
Release of new version kibana-prometheus-exporter 7.16.3

### ISSUE THREAD

**Issue by arjunav123** [pjhampton/kibana-prometheus-exporter#252]
We are upgrading the ELK stack to the latest version 7.16.3 as part of log4j issue.
but we noticed kibana-prometheus-exporter version  7.16.3 is not yet released till now. 
The last version released was 7.16.2.
Can you confirm the release of the  kibana-prometheus-exporter version 7.16.3 ?

**Comment by pjhampton** [comment]
Thanks, @arjunav123. Tested and released.

**Comment by arjunav123** [comment]
that was a light-speed release, thank you so much @pjhampton
