### ISSUE TITLE
Kibana v6.4.2 is now available

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#26]
@pjhampton Thank you in advance!

**Comment by pjhampton** [comment]
Thanks for notifying me @nikolay and sorry for the delay 😄 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.2

**Comment by nikolay** [comment]
Thank you very much, @pjhampton!

**Comment by nikolay** [comment]
@pjhampton Actually, the release is missing the plugin - only the source code is there.

**Comment by pjhampton** [comment]
I apologize @nikolay - my bad. It's there now

Thanks for pinging me!
