### ISSUE TITLE
Image on dockerhub

### ISSUE THREAD

**Issue by jasminehung** [pjhampton/kibana-prometheus-exporter#263]
Hi, is there a chance kibana-prometheus-exporter release a docker image on dockerhub? Since this exporter is awesome and updated frequently, really hope one day we can install it directly on kubernetes through pulling docker image :)
Thanks a lot!

**Comment by pjhampton** [comment]
Hey @jasminehung. 

That is a great idea - I love it :-)

I'm defo up for supporting this from 7.17.0/8.0.0, but I need to do my research first - there are a couple of security features I need to do my homework on. I will report back soon, but for now there is no ETA.

**Comment by pjhampton** [comment]
Thanks again for the report! Closing due to https://github.com/pjhampton/kibana-prometheus-exporter/issues/344
