### ISSUE TITLE
Release supporting Kibana 7.17.1

### ISSUE THREAD

**Issue by manuelbs88** [pjhampton/kibana-prometheus-exporter#266]
Hello @pjhampton,
First of all, thanks a lot for your efforts in keeping this Prometheus exporter up to date. I rly prefer this exporter-kibana-plugin rather than the standalone exporter :)

Recently, we have updated our clusters to v7.17.1 (since 7.9.3 is EOL), and together with them, we also updated our Kibana.

We'd like to continue using this Prometheus exporter, but seems that only the 7.17.0 version is supported, not being supported yet the minor 7.17.1

Do you think it would be possible to adapt the exporter to support the 7.17.1 Kibana version?

Thanks in advance!!

**Comment by pjhampton** [comment]
Thanks so much for the kind words and nudge @manuelbs88 🙏🏻 ✨ 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.17.1
