### ISSUE TITLE
get metrics error when kibana 6.5.0  use basic auth

### ISSUE THREAD

**Issue by waney316** [pjhampton/kibana-prometheus-exporter#275]
kibana and es version=6.5.0，and use user/pass to connect，but when i get localhost:5601/_prometheus/metrics occured  some error
![image](https://user-images.githubusercontent.com/23314093/170476501-8dfb0024-e17b-4c6b-afa3-3fb969a1f21f.png)
![image](https://user-images.githubusercontent.com/23314093/170476534-e154a8be-ad5b-406f-968c-a2315a742fd0.png)

**Comment by pjhampton** [comment]
Apologies - I don't support any releases older than 7.10. Need to draw the line somewhere :-)
Please consider forking.
