### ISSUE TITLE
Release for 7.17.5

### ISSUE THREAD

**Issue by sbarrypoppulo** [pjhampton/kibana-prometheus-exporter#278]
Any chance you can release version for 7.17.5 support?

Thanks

**Comment by weastur** [comment]
up

P. S. I'm not an expert in kibana plugin development, but maybe there is a way/reason to set less strict version constraints?

@pjhampton

**Comment by pjhampton** [comment]
Thanks, folks, and apologies for the wait - I was out on paternity and only catching up on FOSS work now.
I will release the latest 7.17 series of plugin support **this week**.

**Comment by PMDubuc** [comment]
Is there a release of this plugin for 7.17.11?  The latest seems to be 7.17.4 and it doesn't work.  The file download looks much smaller than previous versions.  I haven't tried 7.17.3.  Will it work?

**Comment by pjhampton** [comment]
Sorry folks - it's too hard for me to manage a release channel for both v7 and v8 of the Elastic stack. It makes sense also to focus on the strategic upstream releases.
