### ISSUE TITLE
Improvement: Automated releases consuming from upstream

### ISSUE THREAD

**Issue by sbarrypoppulo** [pjhampton/kibana-prometheus-exporter#279]
Many thanks for your work on this project. I note a lot of issues asking for releases of specific versions and wonder could the release process be streamlined to consume upstream [kibana releases](https://github.com/elastic/kibana/releases) and trigger releases once tested/validated? Might ease some burden by improving automated releases :)

**Comment by pjhampton** [comment]
Thanks for the feedback @sbarrypoppulo! 

Tell me about it - releasing is super cumbersome. Before I went off on sabbatical I created this https://github.com/pjhampton/kibana-prometheus-exporter/blob/main/.github/workflows/release-plugin.yml

However, I wasn't happy with it. I just needs... more polish. I will pick it up again in the coming weeks to ease the toil on me.

**Comment by pjhampton** [comment]
Thanks again for the report! Closing due to https://github.com/pjhampton/kibana-prometheus-exporter/issues/344
