### ISSUE TITLE
targets does not support proxy domain names, such as foo com/log

### ISSUE THREAD

**Issue by Iatbzh** [pjhampton/kibana-prometheus-exporter#280]
targets does not support proxy domain names, such as foo.com/log
- job_name: 'kibana'
  scrape_interval: '10s'
  metrics_path: '_prometheus/metrics'
  static_configs:
  - targets: ['foo.com/log']
  basic_auth:
    username: 'elastic'
    password: 'changeme'

**Comment by pjhampton** [comment]
Thanks for the bug report, @Iatbzh!

Just so I am clear... You have CNAME record `foo.com/log` pointing at `localhost:5601/_prometheus/metrics` or am I misunderstanding?

**Comment by pjhampton** [comment]
I'm going to time this out. Feel free to reopen it with more info if you want me to look into it.
