### ISSUE TITLE
Error with Kibana 6.0.0

### ISSUE THREAD

**Issue by pauloj95** [pjhampton/kibana-prometheus-exporter#29]
Hi, 

Im having the following error in target after install the plugin w/ Kibana 6.0.0,

![image](https://user-images.githubusercontent.com/37109548/47148367-77342b80-d2c8-11e8-84fb-2bd3a2928b90.png)

Can you help ?

Thanks
Regards,

**Comment by pjhampton** [comment]
Hmm, it looks like you are using a newer version of prometheus. I will update all the releases on the weekend :+1:

**Comment by pjhampton** [comment]
Hi @pauloj95 - this should be fixed now. Thanks for letting me know 👍

**Comment by pauloj95** [comment]
HI,

Thanks alot for your attention,
But now I'm getting the following error, plugn not working properly

I've kibana-remove the plugin, restarted services/machine and kibana-install this new version, I've the following error, in kibana log's.

> 
Oct 26 14:55:28 pj-elk kibana[815]: {"type":"error","@timestamp":"2018-10-26T13:55:28Z","tags":[],"pid":815,"level":"error","message":"Uncaught error: Cannot read property '1m' of undefined","error":{"message":"Uncaught error: Cannot read property '1m' of undefined","name":"TypeError","stack":"TypeError: Uncaught error: Cannot read property '1m' of undefined\n    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:14:34)\n    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)\n    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)\n    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:198:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1073:14)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1019:12)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"}}
> Oct 26 14:55:28 pj-elk kibana[815]: Debug: internal, implementation, error
> Oct 26 14:55:28 pj-elk kibana[815]:     TypeError: Uncaught error: Cannot read property '1m' of undefined
> Oct 26 14:55:28 pj-elk kibana[815]:     at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:14:34)
> Oct 26 14:55:28 pj-elk kibana[815]:     at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)
> Oct 26 14:55:28 pj-elk kibana[815]:     at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)
> Oct 26 14:55:28 pj-elk kibana[815]:     at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:198:22)
> Oct 26 14:55:28 pj-elk kibana[815]:     at emitTwo (events.js:106:13)
> Oct 26 14:55:28 pj-elk kibana[815]:     at Request.emit (events.js:191:7)
> Oct 26 14:55:28 pj-elk kibana[815]:     at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1073:14)
> Oct 26 14:55:28 pj-elk kibana[815]:     at emitOne (events.js:101:20)
> Oct 26 14:55:28 pj-elk kibana[815]:     at Request.emit (events.js:188:7)
> Oct 26 14:55:28 pj-elk kibana[815]:     at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1019:12)
> Oct 26 14:55:28 pj-elk kibana[815]:     at emitNone (events.js:91:20)
> Oct 26 14:55:28 pj-elk kibana[815]:     at IncomingMessage.emit (events.js:185:7)
> Oct 26 14:55:28 pj-elk kibana[815]:     at endReadableNT (_stream_readable.js:974:12)
> Oct 26 14:55:28 pj-elk kibana[815]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> Oct 26 14:55:28 pj-elk kibana[815]:     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
> Oct 26 14:55:28 pj-elk kibana[815]: {"type":"response","@timestamp":"2018-10-26T13:55:28Z","tags":[],"pid":815,"method":"get","statusCode":500,"req":{"url":"/_prometheus/metrics","method":"get","headers":{"host":"192.168.56.101:5601","user-agent":"Prometheus/2.4.3","accept":"text/plain;version=0.0.4;q=1,*/*;q=0.1","accept-encoding":"gzip","x-prometheus-scrape-timeout-seconds":"5.000000"},"remoteAddress":"192.168.56.101","userAgent":"192.168.56.101"},"res":{"statusCode":500,"responseTime":38,"contentLength":9},"message":"GET /_prometheus/metrics 500 38ms - 9.0B"}
> 

Regards,
Paulo Jesus

**Comment by pjhampton** [comment]
Hmm - looking.

**Comment by pjhampton** [comment]
Sorry, @pauloj95 - my bad. The api changed in 6.4.0 and I accidentally used that reference in this release. That should be good now.

**Comment by pauloj95** [comment]
Yes, now its working like a charm, 

THanks a lot!
