### ISSUE TITLE
Readme with explanation for metrics data ?

### ISSUE THREAD

**Issue by amithrh** [pjhampton/kibana-prometheus-exporter#30]
Is it possible for any explanation for metric data being exported by this exporter ? e.g : kibana_plugin_kibana_prometheus_exporter ? what is the significance of this metric?

**Comment by pjhampton** [comment]
valid point @amithrh. I will whip something together soon. I also accept PRs :)
As for what that does, it checks the health of the plugin - 1 = green, 0.5 yellow and 0 red

**Comment by pjhampton** [comment]
Yeah, sure. Just shut down the elastic search instance.

**Comment by pjhampton** [comment]
Hey. 

I added some detail here: https://github.com/pjhampton/kibana-prometheus-exporter/wiki

Thanks for the suggestion and pushing this project forward 😄

**Comment by amithrh** [comment]
Thanks Peter , its nice .
