### ISSUE TITLE
[Support Request] Support for Task Manager API stats

### ISSUE THREAD

**Issue by nicholas-r-king** [pjhampton/kibana-prometheus-exporter#305]
Kibana exposes various stats for Task Manager which is responsible for critical things like alerting, actions, reporting, and other persistent background tasks. It would be nice to be able to scrape these alongside the current Kibana stats for better monitoring, especially for places that utilize Kibana in mission critical workloads (as an alerting platform). The endpoint already exposes the stats as JSON and at a set interval, it should be theoretically possible to add these to the exporter. Willing to also test it out and submit MR's if accepting them.

**Comment by pjhampton** [comment]
Hey @nicholas-r-king,

I am aware of the task manager. I certainly think this is a good suggestion. 
I would definitely be supportive of adding a new endpoint to expose these metrics, and would love if you contributed it. I am also happy to advise on the implementation if you require help.

**Comment by pjhampton** [comment]
Thanks again for the report! Closing due to https://github.com/pjhampton/kibana-prometheus-exporter/issues/344
