### ISSUE TITLE
Is there a release for 7.17.11?

### ISSUE THREAD

**Issue by PMDubuc** [pjhampton/kibana-prometheus-exporter#314]
I've tried 7.17.4 and 7.17.3 and neither of them work.  I'm upgrading from 7.8.1 to 7.17.11 and need the plugin for monitoring since 7.8.1 plugin doesn't work either.  Any ideas?

**Comment by pjhampton** [comment]
I'm sorry @PMDubuc. It's too much of a headache for me to manage a release branch for both 7 and 8 versions of the elastic stack.
