### ISSUE TITLE
Release for kibana 8.9.0

### ISSUE THREAD

**Issue by mpostument** [pjhampton/kibana-prometheus-exporter#317]
Hello, can you please build plugin version for kibana 8.9.0

**Comment by mpostument** [comment]
@pjhampton can you please release new version?

**Comment by pjhampton** [comment]
Thanks for the nudge @mpostument!
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/8.9.0

**Comment by mpostument** [comment]
Thanks @pjhampton
