### ISSUE TITLE
Abnormal value of kibana_status

### ISSUE THREAD

**Issue by laletinpv** [pjhampton/kibana-prometheus-exporter#320]
Greetings. I successfully installed the kibanaPrometheusExporter-7.17.4.zip plugin to kibana:7.17.4. When requesting metrics, I get: ```kibana_status -1```, not ```kibana_status 1```. Although in http://kibana_ip:5601/status I see: Kibana status is Green.

**Comment by pjhampton** [comment]
Hey @laletinpv,

Thanks for reporting! Unfortunately, I [don't have the time to maintain the 7.x branch of this plugin](https://github.com/pjhampton/kibana-prometheus-exporter/blob/main/RELEASES.md#-releases-), as well as the 8.x. My advice is that if it is causing issues that fork the project and attempt to fix yourself. Sorry about that.
