### ISSUE TITLE
Elastic 6.4.3 is available

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#33]
@pjhampton Please, release a compatible version. Thanks!

**Comment by pjhampton** [comment]
Thanks as always @nikolay 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.3

You will want to check back in a couple of weeks. I will be adding support for authentication and ssl
Also, some of the metrics names have changed to make compatible with the new Prometheus so you may need to update your dashboard

**Comment by nikolay** [comment]
Thank you, @pjhampton!
