### ISSUE TITLE
new kibana version dosen't support

### ISSUE THREAD

**Issue by like-inspur** [pjhampton/kibana-prometheus-exporter#4]
I install newest version kibana, and install 6.1.1 version plugin, but it doesn't support. Error is like this:
Attempting to transfer from http://10.110.17.48/monitor/kibana-prometheus-exporter-6.1.1.zip
Transferring 465820 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by pjhampton** [comment]
Hey @like-inspur 

Something doesn't seem quite right here. Did you follow the [installation instructions](https://github.com/pjhampton/kibana-prometheus-exporter#installing)?

It seems that you have not added this to the plugins directory. Also, are you using kibana 6.1.1?

**Comment by sergeohl** [comment]
@like-inspur you need the same version as kibana. 

Ask to @pjhampton to add the your version (6.2.4)

**Comment by like-inspur** [comment]
@pjhampton @sergeohl I need 6.2.4 version kibana plugin. Thank you!

**Comment by pjhampton** [comment]
Yes, @sergeohl is correct - needs a new release. See this: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.2.4
I / we should probably go through and all for 6.x.x
