### ISSUE TITLE
Explanation about some of the Kibana metrics exported is missing

### ISSUE THREAD

**Issue by Harish-Sridhar** [pjhampton/kibana-prometheus-exporter#46]
The Kibana-prometheus-exporter is exporting some metrics like the following:

kibana_response_average 0
kibana_response_max 0
kibana_concurrent_connections 5
kibana_os_load1 2.2490234375
kibana_os_load5 2.22802734375
kibana_os_load15 2.90576171875

The information about these metrics are missing in the Wiki page.
For example, what is the base unit used for the kibana response metric?

**Comment by pjhampton** [comment]
done.
