### ISSUE TITLE
6.2.4 plugin install failed

### ISSUE THREAD

**Issue by like-inspur** [pjhampton/kibana-prometheus-exporter#6]
I download kibana-prometheus-exporter-6.2.4.zip and add to my local repo. When I execute kibana-plugin install command, error outuputs "No kibana plugins found in archive"
# ./kibana-plugin install http://10.110.17.48/monitor/kibana-prometheus-exporter-6.2.4.zip
Attempting to transfer from http://10.110.17.48/monitor/kibana-prometheus-exporter-6.2.4.zip
Transferring 465821 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
# ./kibana version
6.2.4

**Comment by pjhampton** [comment]
@like-inspur I will look into why this is. In the meantime you can unzip that folder in the directory and delete the top level zip. Thanks

**Comment by like-inspur** [comment]
I think you should support a install package like this(https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases), not a source code package. Look forward to your reply, thanks.

**Comment by pjhampton** [comment]
Yeah, @like-inspur - I think this is a good suggestion. I will make it so in the coming days.
Did you manage to get this installed ok in the end?

**Comment by like-inspur** [comment]
I try to unzip package to /opt/kibana/plugins/ dir, but it seems not work.

**Comment by pjhampton** [comment]
@like-inspur so the contents of the plugin are in a folder called `/opt/kibana/plugins/prometheus-kibana-exporter`?

**Comment by like-inspur** [comment]
Yes. and kibana can't start because of this plugin. The output of kibana is like this:
{"type":"log","@timestamp":"2018-06-01T01:43:58Z","tags":["info","optimize"],"pid":246,"message":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timelion, kibana-prometheus-exporter and kibana. This may take a few minutes"}

**Comment by pjhampton** [comment]
I see @like-inspur - this is normal behaviour. It takes like 3/4 minutes to compile and then starts up with Kibana itself. If it still isn't working after a couple of minutes - is there any other logs?

**Comment by like-inspur** [comment]
No, I wait for a long time, but there isn't any other log, and kibana can't start still.

**Comment by pjhampton** [comment]
Ok, I'm aware of the slow compilation times but it _should_ finish. I will reach out to the Kibana developers and get back to you in this thread.

**Comment by pjhampton** [comment]
Hey @like-inspur 

Please see: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.2.4

That package should install fine now. Thanks
