### ISSUE TITLE
Prometheus page is not visible on kibana page when searchguard enabled

### ISSUE THREAD

**Issue by ysundar** [pjhampton/kibana-prometheus-exporter#67]
We have installed kibana-promethues-exporter plugin in kibana. This plugin is working fine without any issues without searchguard. Promotues page is not visible in kibana page when we install searchguard plugin. 
We are using 6.6.1 version for kibana, promtues and searchguard.
**Configurations** :-: 
server.ssl.enabled: true
server.ssl.certificate: /path/to/your/server.crt
server.ssl.key: /path/to/your/server.key

**we are getting below error message in kibana logs** 
{"type":"error","@timestamp":"2019-04-16T08:44:54Z","tags":[],"pid":1,"level":"error","error":{"message":"Error: self signed certificate","name":"RequestError","stack":"RequestError: Error: self signed certificate\n    at new RequestError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/usr/share/kibana/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.onRequestError (/usr/share/kibana/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:189:13)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:189:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"Error: self signed certificate"}
**Kibana Screenshot :-**
![Prometues](https://user-images.githubusercontent.com/30171464/56207796-47929000-606d-11e9-8b55-042a8ab65b94.PNG)

**Comment by pjhampton** [comment]
Thanks @ysundar! 

We're looking at SSL here: https://github.com/pjhampton/kibana-prometheus-exporter/issues/3 but will keep this open because of searchguard.

**Comment by pjhampton** [comment]
timing this issue out.
