### ISSUE TITLE
6.3.0 support

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#7]
Any ETA?

**Comment by pjhampton** [comment]
Now! https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.0 😄 

Thanks for your support @nikolay ✨ ⭐️ 
Let me know if you need any help.

**Comment by nikolay** [comment]
After looking into other plugins, it seems that you need to have a base folder of `kibana`, and then a folder with the plugin slug underneath with no versioning, i.e., in this case, the container folder path should be `kibana/prometheus-exporter` and not `kibana-prometheus-exporter-6.3.0` like it is right now.

**Comment by nikolay** [comment]
Lastly, all your other release names are without a `v` prefix. 😄

**Comment by pjhampton** [comment]
Thanks for your feedback @nikolay 
I have just looked into this and you are right. I will try and sort out these releases this week! 

Thanks again!

**Comment by nikolay** [comment]
Thanks, @pjhampton! Please, reopen the issue, then. 😉

**Comment by nikolay** [comment]
@pjhampton I think, you can reuse the project structure from this widely-used plugin: https://github.com/sivasamyk/logtrail

It also follows the best practice of building against Kibana's built-in packages, and not install the outdated and deprecated ones from NPM.

**Comment by pjhampton** [comment]
Hey @nikolay 

Can you please test the new directory in https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.0 for me?

I didn't realize that kibana had a `npm run-script build` script which does this for you. Let me know if it installs ok and I will backfit versions

**Comment by nikolay** [comment]
@pjhampton It works, but could you please rename the plugin to just `prometheus-exporter`? The repository here makes sense to be prefixed with `kibana-`, but a Kibana plugin does not need such prefix.

**Comment by pjhampton** [comment]
Sure, @nikolay - I'd love a PR if you've got time :smile:

**Comment by nikolay** [comment]
@pjhampton I'd love to, but right now `yarn kbn bootstrap` doesn't work for me and I can't spend time on fixing due to other priorities. I was going to try the most simple thing: install the newest Kibana environment, create an empty plugin with its toolchain, and then just put your code into the proper places, and that would ensure it's done by the book... as of now. I'm not sure about the older versions though.

**Comment by pjhampton** [comment]
That's fine @nikolay - thanks for the support regardless. 
I have updated this and I agree with the new package name.  https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.0

Hope you find this package useful!

**Comment by nikolay** [comment]
Thank you very much, @pjhampton! Great job!
