### ISSUE TITLE
Elastic v7.0.1 and v6.7.2 are now available

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#71]
@pjhampton Please, release compatible artifacts! Big thanks in advance! :bow:

**Comment by pjhampton** [comment]
Thanks @nikolay :shipit: 🚀 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.7.2
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/7.0.1
