### ISSUE TITLE
Feature request for kibana 5.3.0

### ISSUE THREAD

**Issue by eozcany** [pjhampton/kibana-prometheus-exporter#74]
We hava kibana 5.3.0 and want to use kibana exporter for prometheus
If It is possible, could you publish a feature which meet with kibana 5.3.0

**Comment by pjhampton** [comment]
@eozcany i'll see what I can do this weekend

**Comment by pjhampton** [comment]
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/5.3.0

There you go. Please star the repo to show support.

**Comment by eozcany** [comment]
Thank you so much @pjhampton

**Comment by eozcany** [comment]
@pjhampton 

I have installed succesfully
But I cannot see the metrics. 

Could you please advice what I can do?

![image](https://user-images.githubusercontent.com/42844314/58374507-ebfad280-7f47-11e9-8b17-5d2aba9195e2.png)

**Comment by pjhampton** [comment]
can you please share me your kibana config yml file please @eozcany - feel free to leave off sensitive info if there is any

**Comment by eozcany** [comment]
Hello @pjhampton 
Here is the kibana.yml file

Thanks for your investigations.


[kibana.yml.txt](https://github.com/pjhampton/kibana-prometheus-exporter/files/3224265/kibana.yml.txt)

**Comment by pjhampton** [comment]
I installed a fresh version of this with the plugin @eozcany and it works ok. Did you remember to restart kibana once you installed it?

**Comment by eozcany** [comment]
Yes, It works now. :) Awesome. Thank you very much

**Comment by eozcany** [comment]
@pjhampton 

I can scrape kibana_status and a few default metrics,
But When I click on Prometheus tab in kibana, It throws a page as below.
Do you have any idea?

![image](https://user-images.githubusercontent.com/42844314/58441820-e3440100-80ed-11e9-8eed-5974a265f20e.png)

**Comment by pjhampton** [comment]
Hey @eozcany 

Yeah, the bad screen is a bug. I will fix that later on. 
As for the handful of metrics - I'm afraid that is all that is really supplied by the < 5.6 status endpoint so I can't get you much more :( sorry!

**Comment by eozcany** [comment]
No worries, 
I am pushing responsible It team to upgrade it.
Thank you for your all assistances.

**Comment by pjhampton** [comment]
Hope you got sorted @eozcany :-)
