### ISSUE TITLE
The new Prometheus icon has been washed out on Kibana 7

### ISSUE THREAD

**Issue by duhang** [pjhampton/kibana-prometheus-exporter#77]
**Describe the bug**

The Prometheus icon prometheus.svg is white/grey out on Kibana 7.1 (hasn't tried 7.0.1 yet, but guess it will be the same)

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1279" alt="Kibana_and_1__root_logging__home_opc__ssh__and_Dockerfile_—_kibana_—__" src="https://user-images.githubusercontent.com/4796455/58451409-3acf7600-80c8-11e9-8ba7-5155f18fbd44.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pjhampton** [comment]
Agreed. This needs fixed in >7. I'm on it! :+1:

**Comment by nikolay** [comment]
Even the icon for v6 I provided does not look well. I'm trying to fix it.

**Comment by pjhampton** [comment]
The UI is now gone from this plugin due to feedback from numerous users :-)

**Comment by matagyula** [comment]
@pjhampton - for now I'm stuck on version 7.3 of the ELK stack, is there a way to hide the faded Prometheus button from the sidebar? While it is clickable, in my case no actual content loads, just an empty page. With that said, the exporter itself works (as discussed in another issue thread).
![image](https://user-images.githubusercontent.com/38976086/69148964-c523f000-0ad5-11ea-9b88-4bac4b06101a.png)
Thank you!

**Comment by pjhampton** [comment]
Hey @matagyula  

Hmm, it looks like a bug - I can roll forward a special release if you give me the exact version number. Would you mind opening a separate issue for this though?

**Comment by matagyula** [comment]
Hi @pjhampton , absolutely, thank you very much :)
