### ISSUE TITLE
"Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined"

### ISSUE THREAD

**Issue by gogi2811** [pjhampton/kibana-prometheus-exporter#86]
Hi @pjhampton 
 I am getting below error with kibana-exporter version 6.4.0
OS - Linux 16.04

`{"type":"error","@timestamp":"2019-06-12T01:25:46Z","tags":[],"pid":29583,"level":"error","error":{"message":"Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined","name":"TypeError","stack":"TypeError: Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined\n    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:7:68)\n    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:26:15)\n    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:51:5)\n`

Exactly similar to below issue
#49

**Comment by pjhampton** [comment]
looking...

**Comment by pjhampton** [comment]
That should be fixed now @gogi2811. Please confirm

**Comment by gogi2811** [comment]
did you update the release @pjhampton ?

**Comment by pjhampton** [comment]
Yes, I updated the release @gogi2811

**Comment by pjhampton** [comment]
Going to time this out @gogi2811. If you still think there is problems let me know and will reopen.
